### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [laanlabs/CarPoseDemo#1]
> coremlc: Error: unable to read document: /Users/alex/Downloads/CarPoseDemo-master/CarPoseDemo/CarPoseModel.mlmodel
> detail: validator error: unable to deserialize object
> Command CoreMLModelCodegen failed with a nonzero exit code

Xcode 10.2.1, iOS 12.2

**Comment by gofortiss** [comment]
same.

**Comment by leestuartx** [comment]
The reason is because github screwed up the asset, you can see this when you try to open the ml file in notepad. To fix this you have to download the raw ml file from it's location in the repo and I'm not sure if it also ruined the opencv framework but you can download that too here: **https://opencv.org/releases/**  
There was one issue with this line:
`p1 = (p1 / outputSize) * ((double)imageWidth);`

 so I just replaced it with:
`p1 = Point3d(p1.x / outputSize * (double)imageWidth, p1.y / outputSize * (double)imageWidth, p1.z / outputSize * (double)imageWidth);
`

**Comment by willperkins** [comment]
I was able to freshly clone the repo from github, build, and run.  This is the setup I used:

- cloned from:  git@github.com:laanlabs/CarPoseDemo.git
- built with Xcode 11.3.1
- onto an iPhone 6S running iOS 13.3

I suspect if might be an issue related to LFS.  Could you confirm which version of [git lfs](https://git-lfs.github.com/) you have installed?

**Comment by sorianog** [comment]
Edit: @leestuartx's workaround for downloading the raw [CarPoseModel.mlmodel](https://github.com/laanlabs/CarPoseDemo/blob/master/CarPoseDemo/CarPoseModel.mlmodel) got me past the issue! 😄 

Build still fails with the same error as above when I currently have:
- git-lfs 2.10.0
- CarPoseModel.mlmodel sitting at a fat `132 bytes`
- Xcode 11.3.1
- iPhone 11 (simulator, just to test things out)
- Mac OS X 10.15.2

**Comment by willperkins** [comment]
@sorianog which git client are you using?

Also: the app was built to only work on a device (since it relies on a live camera feed).

**Comment by sorianog** [comment]
@willperkins Vanilla git through terminal. Also, I do plan on pushing to an actual device once I can get a successful build. If I can get it to install on the simulator that's progress. I expect it to crash after launch due to the requirements of the camera (nature of AR apps on sims).

**Comment by willperkins** [comment]
running `git lfs init` solved the problem
